In [1]:
#!pip install iobes
#!pip install seqeval
#!pip install sklearn_crfsuite 
#!conda install spacy
#!pip uninstall numpy
#!pip install numpy

import spacy
from spacy.tokens import Doc, SpanGroup
from spacy.matcher import Matcher
from zipfile import ZipFile
from pathlib import Path
#from tqdm import autonotebook as tqdm
from tqdm import tqdm
from spacy.training import biluo_tags_to_spans
import iobes
import re
from itertools import combinations

import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from seqeval import scheme

import sklearn_crfsuite
from collections import Counter


In [2]:
#!python -m spacy download en_core_web_sm
nlp = spacy.load("en_core_web_sm")

In [3]:
data_dir = Path("./data/teaching-dataset")
with (data_dir / "relation_classification_text_train.zip").open("rb") as file:
    zip_file = ZipFile(file)
    with zip_file.open("input.txt") as f:
        sentences = [
            sentence.split("\n") for sentence in f.read().decode("utf-8").split("\n\n")
        ]
with (data_dir / "relation_classification_references_train.zip").open("rb") as file:
    zip_file = ZipFile(file)
    with zip_file.open("references.txt") as f:
        labels = []
        for line in f.read().decode("utf-8").split("\n"):
            relations = []
            for relation in re.finditer(r"\(\((\d+),(\d+)\),\((\d+),(\d+)\)\)", line):
                relation = (
                    (int(relation.group(1)), int(relation.group(2))),
                    (int(relation.group(3)), int(relation.group(4))),
                )
                relations.append(relation)
            labels.append(relations)

In [4]:
def parse_sentence(sentence):
    words = []
    tags = []
    for item in sentence:
        word, tag = item.split(" ")
        words.append(word)
        tags.append(tag)
    doc = Doc(nlp.vocab, words=words)
    doc = nlp(doc)
    tags = iobes.bio_to_bilou(tags)
    doc.ents = biluo_tags_to_spans(doc, tags)
    return doc

In [5]:
wordlist = []
biggerlist = []
for word in sentences[0]:
    #print(word)
    wordlist.append(str(word.split()[0]))
print(wordlist)
biggerlist.append(wordlist)
biggerlist.append('test')
print(biggerlist)

['According', 'two', 'different', 'studies', 'it', 'seems', 'plausible', 'that', 'the', 'Pohang', 'earthquake', 'was', 'induced', 'by', 'EGS', 'operations', '.']
[['According', 'two', 'different', 'studies', 'it', 'seems', 'plausible', 'that', 'the', 'Pohang', 'earthquake', 'was', 'induced', 'by', 'EGS', 'operations', '.'], 'test']


In [6]:
wordlist = []
taglist = []
biggertaglist = []
biggerlist = []
for i in range(len(sentences)):
    for word in sentences[i]:
        wordlist.append(str(word.split()[0]))
        taglist.append(str(word.split()[1]))

        
    biggerlist.append(wordlist)
    biggertaglist.append(taglist)
    
    wordlist = []
    taglist = []
#print(biggerlist)        

In [7]:
#for word in sentences[0]:
#    print(word.split())
#    print(word.split()[0])
#    print(word.split()[1])

In [8]:
labels[0]
#helperlist = []
#for i in range(len(sentences)):
#    if len(labels[i]) > 1:
#        helperlist.append(int(i))
#print(helperlist)

[2, 3, 8, 9, 10, 12, 13, 18, 19, 20, 21, 22, 25, 27, 28, 30, 33, 34, 35, 36, 40, 43, 45, 47, 50, 51, 61, 64, 65, 67, 70, 72, 74, 77, 78, 79, 81, 82, 85, 86, 90, 91, 93, 95, 97, 99, 100, 102, 103, 104, 105, 106, 107, 108, 111, 112, 113, 114, 115, 118, 121, 123, 128, 130, 136, 138, 140, 145, 146, 149, 151, 155, 157, 159, 160, 170, 173, 174, 177, 179, 180, 182, 183, 185, 193, 194, 195, 197, 200, 202, 205, 209, 210, 211, 212, 220, 227, 228, 229, 230, 232, 233, 236, 238, 239, 240, 241, 246, 249, 252, 262, 264, 266, 268, 271, 275, 277, 279, 280, 284, 288, 294, 296, 301, 302, 303, 305, 307, 309, 312, 314, 316, 317, 320, 322, 323, 324, 325, 335, 338, 340, 343, 344, 346, 347, 349, 357, 359, 362, 369, 372, 373, 374, 382, 385, 388, 389, 390, 391, 392, 393, 394, 396, 397, 400, 401, 403, 407, 409, 410, 411, 413, 415, 422, 427, 433, 434, 437, 441, 442, 446, 448, 449, 450, 451, 452, 453, 454, 455, 456, 458, 460, 464, 466, 467]


In [9]:
# TODO: for each sentence, get list of event spans 
helperarray = np.zeros(())
for i in range(len(sentences)):
    #print(labels[i])
    for entries in labels[i]:
        #print(entries)
        for numbers in entries:
            #print(numbers)
            for singlets in numbers:
                print(i, singlets)
                

0 14
0 16
0 9
0 11
1 49
1 55
1 58
1 59
2 0
2 4
2 14
2 21
2 8
2 11
2 14
2 21
3 5
3 6
3 11
3 13
3 5
3 6
3 14
3 18
3 5
3 6
3 24
3 26
3 5
3 6
3 29
3 31
3 5
3 6
3 32
3 33
3 5
3 6
3 35
3 38
3 0
3 2
3 11
3 13
3 0
3 2
3 14
3 18
3 0
3 2
3 24
3 26
3 0
3 2
3 29
3 31
3 0
3 2
3 32
3 33
3 0
3 2
3 35
3 38
4 32
4 39
4 43
4 46
5 0
5 2
5 9
5 15
6 33
6 37
6 0
6 1
7 0
7 2
7 5
7 8
8 25
8 28
8 36
8 38
8 20
8 24
8 36
8 38
8 7
8 9
8 36
8 38
9 0
9 2
9 4
9 7
9 0
9 2
9 14
9 17
10 12
10 22
10 3
10 8
10 24
10 32
10 3
10 8
11 1
11 5
11 8
11 12
12 0
12 7
12 10
12 11
12 0
12 7
12 12
12 13
12 0
12 7
12 14
12 17
12 0
12 7
12 18
12 20
12 0
12 7
12 22
12 26
13 0
13 1
13 4
13 7
13 4
13 7
13 11
13 13
13 4
13 7
13 14
13 15
13 4
13 7
13 16
13 17
13 4
13 7
13 18
13 19
14 0
14 1
14 16
14 19
15 1
15 4
15 6
15 14
16 1
16 6
16 12
16 13
17 5
17 6
17 7
17 8
18 0
18 2
18 5
18 7
18 0
18 2
18 10
18 11
18 20
18 21
18 17
18 18
19 26
19 28
19 30
19 33
19 26
19 28
19 34
19 35
19 26
19 28
19 36
19 37
19 26
19 28
19 39
19 40
19 26
19 28
19 

In [10]:
print(len(labels[467]))
print(len(sentences[0]))
#helper = np.zeros((len(sentences[0]), len(sentences[0])))
helper = np.zeros(len(sentences[0]))
print(helper)

for entry in labels[0][0]:
    print(entry)
    for numbers in entry:
        print(numbers)
        helper[numbers-1] = 1
print(helper)

6
17
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(14, 16)
14
16
(9, 11)
9
11
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0.]


In [11]:
jcount = 0
for j in helper:
    jcount += 1
    if j > 0:
        print(jcount)

9
11
14
16


In [12]:
print(labels[1][0][0][0])
print(labels[1][0][1][0])

49
58


In [13]:
print(labels[2])
doc = parse_sentence(sentences[2])
doc.ents

[((0, 4), (14, 21)), ((8, 11), (14, 21))]


(Pneumatic drilling in mines,
 mining using explosives,
 fine - ultra fine crystalline silica dust)

In [14]:
#new df with 1 line per sentence 
sentence_number=[]
wordlist = []
taglist = []
POSlist = []
DEPlist = []
customclass = []

biggerlist = []
biggertaglist = []
biggerPOSlist = []
biggerDEPlist = []
for i in range(len(sentences)):
    if labels[i][0][0][0] < labels[0][0][1][0]:
        customclass.append('0')
    elif labels[i][0][0][0] >= labels[0][0][1][0]:
        customclass.append('1')
for i in range(len(sentences)):
    sentence_number.append(str(i))
    
    for word in sentences[i]:
        wordlist.append(str(word.split()[0]))
        taglist.append(str(word.split()[1]))

    doc = parse_sentence(sentences[i])
    for token in doc:
        POSlist.append(token.pos_)
        DEPlist.append(token.dep_)
            

    biggerlist.append(wordlist)
    biggertaglist.append(taglist)
    biggerPOSlist.append(POSlist)
    biggerDEPlist.append(DEPlist)
    
    wordlist = []
    taglist = []
    POSlist = []
    DEPlist = []

train_data = {'Sentence #': sentence_number, 'Wordlist': biggerlist, 'Taglist': biggertaglist, 'POS': biggerPOSlist, 'DEP': biggerDEPlist, 'customclass': customclass,}
#train_data = {'Sentence #': sentence_number, 'Wordlist': str(biggerlist), 'Taglist': str(biggertaglist), 'POS': str(biggerPOSlist), 'DEP': str(biggerDEPlist), 'customclass': customclass,}
df = pd.DataFrame(data=train_data)
print(df)
#df.to_dict()
#print(df)
#df.to_dict('records')
#print(df)
#df.to_dict('split')
#print(df)

    Sentence #                                           Wordlist  \
0            0  [According, two, different, studies, it, seems...   
1            1  [Signs, and, symptoms, include, :, Dyspnea, (,...   
2            2  [Pneumatic, drilling, in, mines, and, less, co...   
3            3  [Interleukin-1, inhibitors, ,, such, as, canak...   
4            4  [Two, of, the, reviews, postulate, that, exerc...   
..         ...                                                ...   
463        463  [Dental, fluorosis, (, also, termed, mottled, ...   
464        464  [The, detergent, causes, the, vessel, to, coll...   
465        465  [Large, segmental, hemangiomas, of, the, head,...   
466        466  [Following, a, strain, or, partial, rupture, o...   
467        467  [High, infection, rates, for, diseases, such, ...   

                                               Taglist  \
0    [O, O, O, O, O, O, O, O, O, B-EVENT, I-EVENT, ...   
1    [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ... 

In [15]:
df.isnull().sum()

df = df.fillna(method='ffill')
#df['Sentence #'].nunique(), df.Wordlist.nunique(), df.Taglist.nunique(), df.customclass.nunique()
#print(df['Sentence #'].nunique())
#print(df.Wordlist.nunique())
#print(df.Taglist.nunique())
#print(df.CustomClass.nunique())

#df.groupby('Tag').size().reset_index(name='counts')
#print(df.groupby('Tag').size().reset_index(name='counts'))

df.groupby('customclass').size().reset_index(name='counts')
print(df.groupby('customclass').size().reset_index(name='counts'))

#X = df.drop('Tag', axis=1)
X = df.drop('customclass', axis=1)
#print(X)

v = DictVectorizer(sparse=False)

X = v.fit_transform(X.to_dict('records'))

for i in range(10):
    print(X[i])
    
#y = df.Tag.values
y = df.customclass.values
classes = np.unique(y)
classes = classes.tolist()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)
X_train.shape, y_train.shape

  customclass  counts
0           0     314
1           1     154
[1. 0. 0. ... 0. 0. 0.]
[2. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[1. 1. 1. ... 0. 0. 0.]
[1. 1. 0. ... 0. 0. 0.]
[1. 1. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]
[1. 0. 0. ... 0. 0. 0.]


((374, 4015), (374,))

In [16]:
per = Perceptron(verbose=10, n_jobs=-1, max_iter=5)
per.partial_fit(X_train, y_train, classes)
#per.fit(X_train, y_train, classes, coef_init = )

-- Epoch 1
Norm: 116.55, NNZs: 1881, Bias: -22.000000, T: 374, Avg. loss: 223.491979
Total training time: 0.00 seconds.


Perceptron(max_iter=5, n_jobs=-1, verbose=10)

In [17]:
#per.partial_fit(X_train, y_train, classes)

In [18]:
new_classes = classes.copy()
print(new_classes)

['0', '1']


In [19]:
print(classification_report(y_pred=per.predict(X_test), y_true=y_test))

              precision    recall  f1-score   support

           0       0.75      0.66      0.70        64
           1       0.42      0.53      0.47        30

    accuracy                           0.62        94
   macro avg       0.59      0.59      0.59        94
weighted avg       0.65      0.62      0.63        94



In [20]:
import sys
np.set_printoptions(threshold=sys.maxsize)
print(per.predict(X_test))
print(y_test)

['0' '1' '1' '0' '1' '1' '1' '0' '1' '0' '0' '1' '0' '1' '0' '1' '1' '0'
 '0' '0' '0' '0' '0' '0' '0' '1' '0' '0' '0' '0' '0' '0' '1' '1' '1' '0'
 '1' '1' '0' '1' '0' '1' '0' '1' '0' '1' '0' '0' '0' '1' '0' '0' '0' '0'
 '1' '0' '1' '1' '0' '1' '0' '0' '0' '0' '1' '0' '1' '1' '0' '0' '1' '0'
 '1' '1' '1' '0' '0' '0' '0' '1' '1' '1' '0' '0' '1' '0' '1' '0' '0' '0'
 '0' '0' '0' '1']
['0' '0' '1' '0' '1' '0' '0' '1' '1' '0' '0' '1' '1' '0' '0' '0' '0' '0'
 '0' '0' '0' '0' '0' '1' '0' '0' '0' '0' '1' '0' '0' '1' '0' '0' '1' '1'
 '0' '0' '0' '0' '0' '0' '0' '1' '1' '1' '1' '0' '0' '1' '0' '0' '1' '0'
 '0' '0' '1' '0' '0' '1' '0' '0' '0' '0' '0' '1' '1' '0' '1' '0' '1' '0'
 '1' '0' '0' '0' '0' '0' '1' '1' '0' '1' '0' '1' '1' '1' '0' '0' '0' '0'
 '0' '0' '0' '0']


In [21]:
def extract_active_passive(doc):
    # https://stackoverflow.com/questions/74528441/detect-passive-or-active-sentence-from-text
    passive_rules = [
        [
            {"DEP": "nsubjpass"},
            {"DEP": "aux", "OP": "*"},
            {"DEP": "auxpass"},
            {"TAG": "VBN"},
        ],
        [
            {"DEP": "nsubjpass"},
            {"DEP": "aux", "OP": "*"},
            {"DEP": "auxpass"},
            {"TAG": "VBZ"},
        ],
        [
            {"DEP": "nsubjpass"},
            {"DEP": "aux", "OP": "*"},
            {"DEP": "auxpass"},
            {"TAG": "RB"},
            {"TAG": "VBN"},
        ],
    ]
    # Create pattern to match active voice use
    active_rules = [
        [{"DEP": "nsubj"}, {"TAG": "VBD", "DEP": "ROOT"}],
        [{"DEP": "nsubj"}, {"TAG": "VBP"}, {"TAG": "VBG", "OP": "!"}],
        [{"DEP": "nsubj"}, {"DEP": "aux", "OP": "*"}, {"TAG": "VB"}],
        [{"DEP": "nsubj"}, {"DEP": "aux", "OP": "*"}, {"TAG": "VBG"}],
        [{"DEP": "nsubj"}, {"TAG": "RB", "OP": "*"}, {"TAG": "VBG"}],
        [{"DEP": "nsubj"}, {"TAG": "RB", "OP": "*"}, {"TAG": "VBZ"}],
        [{"DEP": "nsubj"}, {"TAG": "RB", "OP": "+"}, {"TAG": "VBD"}],
    ]
    matcher = Matcher(nlp.vocab)
    matcher.add("Passive", passive_rules)
    matcher.add("Active", active_rules)
    matches = matcher(doc)
    matches = [
        (nlp.vocab.strings[match_id], doc[start:end])
        for match_id, start, end in matches
    ]
    return matches


def predict(sentence):
    doc = parse_sentence(sentence)
    matches = extract_active_passive(doc)
    predictions = []
    for ent_1, ent_2 in combinations(doc.ents, 2):
        for match_type, match_span in matches:
            if SpanGroup(doc, spans=[ent_1, ent_2, match_span]).has_overlap:
                match_active = match_type == "Active"
                if match_active:
                    predictions.append(
                        ((ent_1.start, ent_1.end), (ent_2.start, ent_2.end))
                    )
                    break
                else:
                    predictions.append(
                        ((ent_2.start, ent_2.end), (ent_1.start, ent_1.end))
                    )
                    break
    return predictions

In [22]:
doc = parse_sentence(sentences[0])
matches = extract_active_passive(doc)
print(doc)
for match_type, match_span in matches:
    print("\t{}: {}".format(match_type, match_span.text))

According two different studies it seems plausible that the Pohang earthquake was induced by EGS operations . 
	Active: it seems
	Passive: earthquake was induced


In [23]:
idx = 5
doc = parse_sentence(sentences[idx])
pred = predict(sentences[idx])
print(doc)
print("Ground truth:")
for cause, effect in labels[idx]:
    print("\t{} -> {}".format(doc[cause[0]:cause[1]], doc[effect[0]:effect[1]]))
print("Predictions:")
for cause, effect in pred:
    print("\t{} -> {}".format(doc[cause[0]:cause[1]], doc[effect[0]:effect[1]]))


Serum sickness can be developed as a result of exposure to antibodies derived from animals . 
Ground truth:
	Serum sickness -> exposure to antibodies derived from animals
Predictions:
	exposure to antibodies derived from animals -> Serum sickness


In [24]:
predictions = []
#for sentence in tqdm.tqdm(sentences):
for sentence in tqdm(sentences):
    predictions.append(predict(sentence))

100%|███████████████████████████████████████████████████████████████████████████████| 468/468 [00:03<00:00, 142.21it/s]


In [25]:
def evaluate(predictions, references, micro_avg=True):
    tp = []
    fp = []
    fn = []
    for prediction, reference in zip(predictions, references):
        tp.append(len(set(prediction) & set(reference)))
        fp.append(len(set(prediction) - set(reference)))
        fn.append(len(set(reference) - set(prediction)))
    if micro_avg:
        tp = [sum(tp)]
        fp = [sum(fp)]
        fn = [sum(fn)]
    precision = [0 if tp[i] == 0 else tp[i] / (tp[i] + fp[i]) for i in range(len(tp))]
    recall = [0 if tp[i] == 0 else tp[i] / (tp[i] + fn[i]) for i in range(len(tp))]
    f1 = [
        0
        if precision[i] * recall[i] == 0
        else 2 * precision[i] * recall[i] / (precision[i] + recall[i])
        for i in range(len(tp))
    ]
    precision = sum(precision) / len(precision)
    recall = sum(recall) / len(recall)
    f1 = sum(f1) / len(f1)
    return precision, recall, f1


micro_precision, micro_recall, micro_f1 = evaluate(predictions, labels, True)
macro_precision, macro_recall, macro_f1 = evaluate(predictions, labels, False)

print("Micro Precision: {:.2f}".format(micro_precision))
print("Micro Recall: {:.2f}".format(micro_recall))
print("Micro F1: {:.2f}".format(micro_f1))
print("Macro Precision: {:.2f}".format(macro_precision))
print("Macro Recall: {:.2f}".format(macro_recall))
print("Macro F1: {:.2f}".format(macro_f1))


Micro Precision: 0.47
Micro Recall: 0.22
Micro F1: 0.30
Macro Precision: 0.26
Macro Recall: 0.27
Macro F1: 0.26
